services:
  loxhuebridge:
    build: .
    container_name: loxhuebridge
    restart: always
    
    # WICHTIG: Host Network für korrekte UDP Kommunikation mit Loxone
    network_mode: "host"
    
    environment:
      - TZ=Europe/Vienna
      # Optional: Falls du den Web-Port ändern willst (Standard 8555)
      # - HTTP_PORT=8555 
      
    volumes:
      # WICHTIG: Wir mounten den lokalen Ordner "./data" in den Container
      # Dort liegen dann config.json und mapping.json sicher.
      - ./data:/app/data